<a href="https://colab.research.google.com/github/HimaSava/Josephus-Problem/blob/main/Josephus_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import numpy as np

n = 19
x = np.arange(1,n+1)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [122]:
while np.size(x)>=1:
  for i in range(n):
    if(np.size(x)==0):
      break
    print(x)
    print("The killer: " , x[i])
    
    #print(i)
    #print(n)
    if(i==n-1):
      print("The person killed" , x[0])
      x = np.delete(x,0)
      n-=1
      break  
    else:
      print("The person killed:" , x[i+1])
      print()
      x = np.delete(x,i+1)
      n-=1
      if(i==n-1):
        break
    

  

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The killer:  1
The person killed 2

[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The killer:  3
The person killed 4

[ 1  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The killer:  5
The person killed 6

[ 1  3  5  7  8  9 10 11 12 13 14 15 16 17 18 19]
The killer:  7
The person killed 8

[ 1  3  5  7  9 10 11 12 13 14 15 16 17 18 19]
The killer:  9
The person killed 10

[ 1  3  5  7  9 11 12 13 14 15 16 17 18 19]
The killer:  11
The person killed 12

[ 1  3  5  7  9 11 13 14 15 16 17 18 19]
The killer:  13
The person killed 14

[ 1  3  5  7  9 11 13 15 16 17 18 19]
The killer:  15
The person killed 16

[ 1  3  5  7  9 11 13 15 17 18 19]
The killer:  17
The person killed 18

[ 1  3  5  7  9 11 13 15 17 19]
The killer:  19
The person killed 1
[ 3  5  7  9 11 13 15 17 19]
The killer:  3
The person killed 5

[ 3  7  9 11 13 15 17 19]
The killer:  7
The person killed 9

[ 3  7 11 13 15 17 19]
The killer:  11
The person